# Generated by Django 3.0.3 on 2020-02-28 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='room',
            name='last_edit',
        ),
        migrations.AlterField(
            model_name='appoint',
            name='Astatus',
            field=models.SmallIntegerField(choices=[(0, 'appointed'), (1, 'processing'), (2, 'waiting'), (3, 'confirmed'), (4, 'cancelled'), (5, 'violated'), (6, 'judge')], default=0, verbose_name='预约状态'),
        ),
        migrations.AlterField(
            model_name='appoint',
            name='Room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appoint_list', to='Appointment.Room', verbose_name='房间号'),
        ),
    ]
