# Generated by Django 3.0.2 on 2020-02-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='Rfinish',
            field=models.TimeField(verbose_name='最迟预约时间'),
        ),
        migrations.AlterField(
            model_name='room',
            name='Rstart',
            field=models.TimeField(verbose_name='最早预约时间'),
        ),
    ]
