# Generated by Django 3.0.3 on 2020-03-01 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0002_auto_20200228_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['Sid'], 'verbose_name': '学生', 'verbose_name_plural': '学生'},
        ),
        migrations.AddField(
            model_name='appoint',
            name='is_canceled',
            field=models.BooleanField(default=False, verbose_name='已取消'),
        ),
        migrations.AlterField(
            model_name='appoint',
            name='Astatus',
            field=models.SmallIntegerField(choices=[(0, 'appointed'), (1, 'processing'), (2, 'waiting'), (3, 'confirmed'), (4, 'violated'), (5, 'judge')], default=0, verbose_name='预约状态'),
        ),
        migrations.AlterModelTable(
            name='appoint',
            table=None,
        ),
        migrations.AlterModelTable(
            name='room',
            table=None,
        ),
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
    ]
