# Generated by Django 3.0.3 on 2020-03-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0003_auto_20200301_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoint',
            name='is_canceled',
        ),
        migrations.AlterField(
            model_name='appoint',
            name='Astatus',
            field=models.SmallIntegerField(choices=[(0, 'canceled'), (1, 'appointed'), (2, 'processing'), (3, 'waiting'), (4, 'confirmed'), (5, 'violated'), (6, 'judge')], default=0, verbose_name='预约状态'),
        ),
    ]
