# Generated by Django 3.0.3 on 2020-03-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0005_auto_20200301_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='Astatus',
            field=models.IntegerField(choices=[(0, 'Canceled'), (1, 'Appointed'), (2, 'Processing'), (3, 'Waiting'), (4, 'Confirmed'), (5, 'Violated'), (6, 'Judged')], default=0, verbose_name='预约状态'),
        ),
    ]
